# Bài 1: Numpy(part 1)
## 1. Tổng quan
- `Numpy` là viết tắt của numerical python, dành cho việc tối ưu tính toán số học
- Cấu trúc dữ liệu nền tảng của numpy là num array
- Numpy array tương tự như list
- Một số đặc điểm nổi bật:
    - Các phần tử buộc phải cùng kiểu dữ liệu (dtype) để tối ưu cho việc tính toán
    - Kích thước np array không thể thay đổi sau khi tạo
    - Tuy nhiên có thể thay đổi giá trị các phần tử
    - Hỗ trợ tính toán element-wise
    - Là nền tảng dựng nên gói `pandas`, tool chính của DA

### 1.1 Tạo numpy array
- Thường import numpy dưới tên `np`

In [1]:
import numpy as np

- Đơn giản nhất là khởi tạo np array từ list, tuple

In [3]:
l = [1, 1.2, 4]
a = np.array(l)

In [4]:
a

array([1. , 1.2, 4. ])

In [6]:
# tyoe n-dimensional
type(a)

numpy.ndarray

In [7]:
# Type of element data type
a.dtype

dtype('float64')

In [8]:
t = (1,2,3,4,5)
a = np.array(t)

In [13]:
a

array([1, 2, 3, 4, 5])

In [14]:
a.dtype

dtype('int64')

- Tạo array các số nguyên liên tiếp (hoặc nhảy 1 khoảng cố định)

In [15]:
range(10)

range(0, 10)

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
np.arange(0,1.000001,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

- Nếu data không cùng kiểu, sẽ được promote lên kiểu tổng quát nhất

In [24]:
# Ví dụ 1: convert all to float
a = np.array([0,1,2, True, False, 3.5])
print(a)
print(a.dtype)

[0.  1.  2.  1.  0.  3.5]
float64


In [25]:
# Ví dụ 2: covert all to str
a = np.array([1,2, True, 'Apple'])

print(a)
print(a.dtype)

['1' '2' 'True' 'Apple']
<U21


In [27]:
# ví dụ 3: covert all to object (not recommend)
# Mục đích của np sinh ra để tối ưu hoá tính toán cho collection chứa các phần tử cùng kiểu
# Vì vậy, không dùng numpy để handle collection của elements khác kiểu

a = np.array([1, 2, True, "Apple", [1,2]])
print(a)
print(a.dtype)

[1 2 True 'Apple' list([1, 2])]
object


/var/folders/gx/0xqp3mnx7vl_hw5j6gyp9wfm0000gn/T/ipykernel_2033/2095677541.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([1, 2, True, "Apple", [1,2]])


- Array 2 chiều (tương tự như nested list)

In [28]:
l = [
    [1,2],
    [3,4]
]


In [29]:
l[0][0]

1

# 2. Thao tác numpy array

## 2.1 Lấy thông tin cơ bản

- Khởi tạo 

In [30]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([[1,2], [3,4], [5,6]])

print(a)
print(b)

[1 2 3 4 5 6 7]
[[1 2]
 [3 4]
 [5 6]]


- Đếm số phần tử - len

In [31]:
len(a)

7

In [32]:
len(b)

3

- Đếm số phần tử - size

In [33]:
a.size

7

In [34]:
b.size

6

- check dtype

In [35]:
a.dtype

dtype('int64')

In [36]:
b.dtype

dtype('int64')

- check số chiều

In [38]:
a.ndim

1

In [39]:
b.ndim


2

- check shape

In [40]:
a.shape


(7,)

In [42]:
b.shape

(3, 2)

## 2.2 Indexing and Slicing 1d-arrays
- Tương tự list

### A) Index/ Slice (read)

In [44]:
# Initialize
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
# First
a[0]

0

In [47]:
# Last elem
a[-1]

11

In [48]:
# 1st to 3rd
a[:3]

array([0, 1, 2])

In [49]:
# 3rd to last
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
# 3rd to second to last
a[2:-1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

### B) Index (write)

In [51]:
# Sửa phần tử đầu thành 99
a[0] =99
a

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
# slice 3 phần tử đầu và thay chúng bằng [90, 80, 70]
a[:3] = [90, 80, 70]
a

array([90, 80, 70,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
l[:3] = [1, 2, 3, 4]
l

[1, 2, 3, 4]

In [ ]:
## 2.3 In