# Numpy

In [1]:
import numpy as np

## 1. Tổng quan
- Giống như list
- Các phần tử của array phải cùng kiểu `dtype`
- Mục đích
    - High performance computing
    - Elementwise computing

In [1]:
# Import
import numpy as np

In [2]:
# Initialize
l = [1, 1.2, True]
a = np.array(l)

In [4]:
# View
a

array([1. , 1.2, 1. ])

In [5]:
# Type
a.dtype

dtype('float64')

In [6]:
# Dtype
a.dtype

dtype('float64')

Multiple ways

In [7]:
# From a list


In [8]:
# From a tuple


In [9]:
# Using arange


In [10]:
# nd array


## 2. Thao tác với numpy array

Basic info

In [11]:
# Size


In [12]:
# Dtype


In [13]:
# Shape


In [14]:
# Dim


### 3. Indexing & Slicing

1D

In [15]:
# Initiate
a = np.arange(12)

In [16]:
# First
a[0]

0

In [17]:
# Last 
a[-1]

11

In [18]:
# 1st to 3rd
a[:3]

array([0, 1, 2])

In [19]:
# 3rd to last
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
# 3rd to second to last
a[2:-1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Start, stop, step
a[::2]

array([ 0,  2,  4,  6,  8, 10])

### B) Index(write)

In [22]:
# Sửa phần từ đầu thành 99
a[0] = 99
a

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
# Slice 3 phần tử đầu và thay chúng bằng [90, 80, 70]
a[:3] = [90, 80, 70]
a

array([90, 80, 70,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
# Slice 3 phần tử đầu và thay chúng bằng [90, 80]
# a[:3] = [90, 80]
# Error: biểu thức gán bên phải phải có số phần tử bằng với slice bên trái

In [25]:
len(a)

12

In [26]:
l = [1,2,3]

In [27]:
l[:2] = [1,2,3,4]
l

[1, 2, 3, 4, 3]

In [28]:
a[:2] = [1000,299]
a

array([1000,  299,   70,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

## 2.3 Indexing and Slicing 2d-arays

In [29]:
# reshape((3,4)) = reshape 3 hàng và 4 cột
# Ưu tiên hàng trước cột sau
a = np.arange(12).reshape((3, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
# Row 1 col 2
# Hàng trước cột sau
a[1,2]

6

In [31]:
# Lấy ra số 10
# Hàng cuối - cột gần cuối (-2)
a[-1,-2]

10

In [32]:
# Lấy ra số 11
a[-1,-1]

11

### B) Slicing

In [33]:
# Row 1 -> Hàng đầu
a[0,:]

array([0, 1, 2, 3])

In [34]:
# Col 1 -> cột đầu
a[:,0]

array([0, 4, 8])

In [35]:
# Lấy cột cuối cùng
a[:,-1]

array([ 3,  7, 11])

In [36]:
# Lấy hai cột giữa
a[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [37]:
# chỉ lấy 3 giá trị đầu của cột đầu tiên
a[0,: 3]

array([0, 1, 2])

In [38]:
# Sub matrix 2 hàng đầu, giao 2 cột cuối
a[:2, -2:]

array([[2, 3],
       [6, 7]])

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
# cột đầu + cột cuối
# vì nó không liên tục nên ta lấy hết toàn bộ các hàng
# tiếp đến tạo ra một list trong list đó chứa [0,-1]
a[:, [0,-1]]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

## 4. Vectorization

In [41]:
a = [1, 2, 4]
b = [5, 6, 7]

In [42]:
a + b

[1, 2, 4, 5, 6, 7]

In [43]:
a = np.arange(-5, 5)
print(a)

[-5 -4 -3 -2 -1  0  1  2  3  4]


Tạo array chứa các elements là bình phương của element trong `a`

In [44]:
l = [1, 2, 3]

In [45]:
[x * 3 for x in l]

[3, 6, 9]

In [46]:
# Add
a + 10

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
# Subtract
a - 10

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6])

In [48]:
# Multiply
a * 10

array([-50, -40, -30, -20, -10,   0,  10,  20,  30,  40])

In [49]:
# Power
a / 10

array([-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4])

In [50]:
# Sqrt
# return nan nếu phép toán không hợp lệ (ví dụ: căn bậc hai của âm)
np.sqrt(a)

/var/folders/gx/0xqp3mnx7vl_hw5j6gyp9wfm0000gn/T/ipykernel_14033/2394712240.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([       nan,        nan,        nan,        nan,        nan,
       0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [51]:
# Mean


In [52]:
# Absolute value
np.abs(a)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

### 5. Filtering (Masking)
- Dùng để lọc (filter) data
- Indexing bằng cách dùng một logical(boolean) array có chiều dài đúng bằng chiều dài của array cần filter

In [53]:
# set seed để reproduce lại kết quả 
np.random.seed(1)

# Tạo ngẫu nhiên 20 số nguyên trong khoảng [-10, 10]
a = np.random.randint(-10, 10, size = 5)

# print
a

array([-5,  1,  2, -2, -1])

In [54]:
a[[True, False, True, False, False]]

array([-5,  2])

In [55]:
a > 0

array([False,  True,  True, False, False])

In [56]:
# Lọc số chẵn
a[a %2 == 0]

array([ 2, -2])

In [57]:
# Lọc số dương
a[a > 0]

array([1, 2])

In [58]:
# Lọc số chẵn và dương
a[(a > 0) & (a % 2 == 0)]

array([2])

In [59]:
# Lọc số lẻ hoặc âm
a [(a % 2 != 0) | (a <0)]

array([-5,  1, -2, -1])

- Toán tử `&` và `|`. Lưu ý phân biệt:
    - `&` vs `and`
    - `|` vs `or`

In [60]:
True and False

False

- `All`: trả về True nến ALL elemnt của array đều là True. Trà về False nếu tồn tại ít nhất 1 phần tử là False 

In [61]:
# Kiểm tra với mọi
np.all([True, True, False])

False

In [62]:
# Kiểm tra tồn tại
np.any([False, False, False])

False

In [63]:
a

array([-5,  1,  2, -2, -1])

In [64]:
np.any(a > 0)

True

# 5. Một số giá trị đặc biệt của numpy
## 5.1 NaN
- Dùng để biểu thị một giá trị missing hoặc kết quả của một phép toán không hợp lệ.
- Viết tắt của Not a Number
- Tương đương với giá trị NA trong R
- Simply means: I don't know the value

In [65]:
# NaN value
np.nan

nan

In [66]:
# Type
type(np.nan)

float

- Các thao tác với nan thường trả về nan (hoặc false)

In [67]:
# Initialize
a = np.array([1, 2, np.nan])
a

array([ 1.,  2., nan])

In [68]:
# Add
a + 3

array([ 4.,  5., nan])

In [69]:
# NaN are not the same
np.nan == np.nan

False

- Thao tác với NaN dung `np.isnan()`

In [70]:
# Wrong (2 NaNs are not the same)
a[a == np.nan]

array([], dtype=float64)

In [71]:
# Lấy ra thằng NaN trong a
a[np.isnan(a)]

array([nan])

In [72]:
# Lấy ra thằng không phải là NaN
a[~np.isnan(a)]

array([1., 2.])

## 5.2. Infty

In [73]:
# Value
np.infty

inf

In [74]:
type(np.infty)

float

In [75]:
a = np.array([1, 2, 3, np.nan, np.infty, -np.infty])
a

array([  1.,   2.,   3.,  nan,  inf, -inf])

In [76]:
# Lọc ta các giá trị không phải infty
a[~np.isinf(a)]

array([ 1.,  2.,  3., nan])

In [77]:
# Lọc ra các giá trị không phải nan
a[~np.isnan(a)]

array([  1.,   2.,   3.,  inf, -inf])

In [78]:
# Lọc ra các giá trị vừa không phải infty vừa không phải nan
a[~np.isinf(a) & ~np.isnan(a)]

array([1., 2., 3.])

## 6. Descriptive statistics (Thống kê mô tả)
- Là hành động collapse data thành một con số tóm tắt một khía cạnh đặc trung của data
- Sẽ học kỹ hơn ở phần review về thống kê

In [79]:
# Initialize
# Giả lập thu nhập của 200 người trong 1 khu vực
# Min: 15 triệu/ tháng
# Max: 80 triệu / tháng

np.random.seed(1)
a = np.random.randint(15, 81, 200)

print(a)
print(a.size)

[52 27 24 20 79 31 16 21 40 65 35 33 26 43 44 29 65 28 24 22 78 76 37 72
 16 15 75 23 28 62 45 18 36 64 72 18 39 58 41 67 56 30 79 40 22 41 40 37
 24 38 42 52 72 53 23 47 49 25 38 30 40 77 61 47 38 70 80 18 15 21 67 17
 36 22 58 35 45 51 22 60 72 28 25 38 22 39 35 47 27 80 75 39 17 25 69 63
 69 30 20 32 57 35 63 37 28 68 25 70 76 71 36 40 29 28 58 21 71 74 30 39
 24 68 51 36 55 64 62 55 60 31 43 60 61 15 44 78 50 68 48 17 63 69 47 43
 70 46 43 23 47 23 65 56 79 39 35 59 30 45 29 34 41 22 68 62 75 49 47 34
 39 53 62 20 78 47 57 45 32 79 75 32 54 50 43 37 53 56 40 63 65 77 59 69
 15 31 34 24 66 25 38 29]
200


In [80]:
# Sắp xếp thu nhập từ thấp đến cao
np.sort(a)

array([15, 15, 15, 15, 16, 16, 17, 17, 17, 18, 18, 18, 20, 20, 20, 21, 21,
       21, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25,
       25, 25, 25, 25, 26, 27, 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 30,
       30, 30, 30, 30, 31, 31, 31, 32, 32, 32, 33, 34, 34, 34, 35, 35, 35,
       35, 35, 36, 36, 36, 36, 37, 37, 37, 37, 38, 38, 38, 38, 38, 39, 39,
       39, 39, 39, 39, 40, 40, 40, 40, 40, 40, 41, 41, 41, 42, 43, 43, 43,
       43, 43, 44, 44, 45, 45, 45, 45, 46, 47, 47, 47, 47, 47, 47, 47, 48,
       49, 49, 50, 50, 51, 51, 52, 52, 53, 53, 53, 54, 55, 55, 56, 56, 56,
       57, 57, 58, 58, 58, 59, 59, 60, 60, 60, 61, 61, 62, 62, 62, 62, 63,
       63, 63, 63, 64, 64, 65, 65, 65, 65, 66, 67, 67, 68, 68, 68, 68, 69,
       69, 69, 69, 70, 70, 70, 71, 71, 72, 72, 72, 72, 74, 75, 75, 75, 75,
       76, 76, 77, 77, 78, 78, 78, 79, 79, 79, 79, 80, 80])

### Measures of central locations
- Mean

In [81]:
# Mean (Tính trung bình cộng) - average
np.mean(a) 

45.35

In [82]:
# Median (Trung vị)
np.median(a)

43.0

In [83]:
# Min
np.min(a)

15

In [84]:
# Max
np.max(a)

80

### Measures of spead
- Variance

In [85]:
# Variance(Phương sai)
np.var(a)

348.4375

In [86]:
# STD (Độ lệch chuẩn) -> căn của phương sai
a.std()

18.666480653835098

In [87]:
# Sum
np.sum(a)

9070

In [88]:
# Marginal summaries


### B) 2d-array

In [97]:
# Initialize
# Giả lập doanh thu 12 tháng của 4 cửa hàng 
# min: 10 triệu / tháng
# max: 20 triệu / tháng

np.random.seed(0)
a = np.random.randint(10,21, size = 48).reshape((12,4))
a

array([[15, 10, 13, 13],
       [17, 19, 13, 15],
       [12, 14, 17, 16],
       [18, 18, 20, 11],
       [16, 17, 17, 18],
       [11, 15, 19, 18],
       [19, 14, 13, 10],
       [13, 15, 10, 12],
       [13, 18, 11, 13],
       [13, 13, 17, 10],
       [11, 19, 19, 10],
       [20, 14, 17, 13]])

In [99]:
pd.DataFrame(a, columns = ["s1", "s2", "s3", "s4"]).to_excel("aa.xlsx", index = False)

- Tổng doanh thu cả năm của tất cả cửa hàng

In [95]:
a.sum()

709

- Tổng doanh thu của từng cửa hàng


In [100]:
# theo axis(trục), pd hay np sẽ ưu tiên dòng trước cột sau
# Across rows
a.sum(axis = 0)

array([178, 186, 186, 159])

- Tổng doanh thu theo từng tháng của 4 cửa hàng

In [101]:
a.sum(axis = 1)

array([51, 64, 59, 67, 68, 63, 56, 50, 55, 53, 59, 64])

- Doanh thu trung bình của 1 cửa hàng trong 1 tháng (coi các cửa hàng và các tháng giống nhau

In [102]:
a.mean()

14.770833333333334

- Doanh thu trung bình mỗi tháng của từng cửa hàng (coi các tháng giống nhau)

In [105]:
a.mean(axis = 0)

array([14.83333333, 15.5       , 15.5       , 13.25      ])

- Doanh thu trung bình của một cửa hàng trong từng tháng (coi các cửa hàng giống nhau)

In [106]:
a.mean(axis = 1)

array([12.75, 16.  , 14.75, 16.75, 17.  , 15.75, 14.  , 12.5 , 13.75,
       13.25, 14.75, 16.  ])

# Tóm Tắt
- Numpy array: 1d, 2d
- Giống như list
- Tính chất:
    - size : có bao nhiêu element, tính toàn bộ các element
    - len : chỉ tính các chiều ngoài cùng
    - ndim
    - shape
- Đặc trưng:
    - Element-wise
    - Filter using masking
    - & |
    - any all

In [89]:
import pandas as pd

In [90]:
pd.DataFrame({"income": a}).to_excel("a.xlsx", index = False)

In [91]:
a

array([52, 27, 24, 20, 79, 31, 16, 21, 40, 65, 35, 33, 26, 43, 44, 29, 65,
       28, 24, 22, 78, 76, 37, 72, 16, 15, 75, 23, 28, 62, 45, 18, 36, 64,
       72, 18, 39, 58, 41, 67, 56, 30, 79, 40, 22, 41, 40, 37, 24, 38, 42,
       52, 72, 53, 23, 47, 49, 25, 38, 30, 40, 77, 61, 47, 38, 70, 80, 18,
       15, 21, 67, 17, 36, 22, 58, 35, 45, 51, 22, 60, 72, 28, 25, 38, 22,
       39, 35, 47, 27, 80, 75, 39, 17, 25, 69, 63, 69, 30, 20, 32, 57, 35,
       63, 37, 28, 68, 25, 70, 76, 71, 36, 40, 29, 28, 58, 21, 71, 74, 30,
       39, 24, 68, 51, 36, 55, 64, 62, 55, 60, 31, 43, 60, 61, 15, 44, 78,
       50, 68, 48, 17, 63, 69, 47, 43, 70, 46, 43, 23, 47, 23, 65, 56, 79,
       39, 35, 59, 30, 45, 29, 34, 41, 22, 68, 62, 75, 49, 47, 34, 39, 53,
       62, 20, 78, 47, 57, 45, 32, 79, 75, 32, 54, 50, 43, 37, 53, 56, 40,
       63, 65, 77, 59, 69, 15, 31, 34, 24, 66, 25, 38, 29])